### ISSUE TITLE
live photo upload system

### ISSUE THREAD

**Issue by Rushi98** [MobileApplicationsClub/Events#5]
1. upload pics during the event itself
2. captions
3. liking the photos to that events activity

**Comment by aayushsingla** [comment]
Any suggestion from your side for storing pics?
@Rushi98

**Comment by Rushi98** [comment]
You can start with any of the two you are comfortable with. Try to keep the code for upload etc. modular so that if there is some issue (ex. we hit 5 GB limit of cloud storage) we are able to swap one for another easily.

**Comment by aayushsingla** [comment]
I was thinking to use Flickr API. i think it is cool for all our needs.
https://www.flickr.com/services/api/

**Comment by Rushi98** [comment]
We can't. Flickr guidelines specifically ask not to use their service as replacement for content server and we should respect that.

https://www.flickr.com/help/guidelines

**Comment by aayushsingla** [comment]
So,if we cant use their API then i will use google drive REST API for it. In database we will use a separate node to store urls for photo and the additional meta-data with it. Linking to other features can be decided once we other features are complete and we have a working this feature.For now, is it ok to have a recycler view for displaying pics, something insta type? And shall there be a separate fragment or an activity for this?

**Comment by Rushi98** [comment]
Separate activity for the main feature. And a fragment to be shown in home activity

**Comment by Rushi98** [comment]
@aayushsingla See https://developer.android.com/training/camera/photobasics to see how to take photos with existing camers apps.

**Comment by aayushsingla** [comment]
@Rushi98  the image chooser i have used gives this option in the status bar when we go to select the image

**Comment by Rushi98** [comment]
Why use an external library when native code is easily available?

**Comment by aayushsingla** [comment]
External Library allows you to select images already stored on phone.For this you wont need any file explorer and you can also limit the number of images to be selected.It also takes care of most things like asking for storage permission. The library is very small.So, i guess we dont need to worry. And it can also be customised. :p

**Comment by Rushi98** [comment]
Native camera apps also allows to select previously captured images. (It also has advantage of filtering out non photo images. So no cat gifs :P ) User is already familiar with native camera ui.

**Comment by aayushsingla** [comment]
I don't think Ui will be a problem because it is simpler then the actual one. However the major advantages of using image picker were:
1.) it doesnot require prescence of any external app like gallery, camera or photos app.
2.)It takes care of all the the permissions to be asked and the cases user denies the permission.

If you still think native camera app is better, I will remove the lib in future commits.

**Comment by Rushi98** [comment]
I do think it's better to use native capabilities than third party libraries as we have all control up from basics.

**Comment by tanmaydixit** [comment]
This will continue in #40
