### ISSUE TITLE
Add Google maps.

### ISSUE THREAD

**Issue by tanmaydixit** [MobileApplicationsClub/Events#8]
A google map activity needs to made.
The button to open it will be in the nav bar. 
For reference check how its done in waves or nmd or icef.

**Comment by Rushi98** [comment]
Better way is to take them from firebase. (Remember this is not necessarily a BITS specific app.)

**Comment by Rushi98** [comment]
Better way is to take them from firebase. (Remember this is not necessarily a BITS specific app)

**Comment by rrgodhorus** [comment]
I'll do this?

**Comment by Rushi98** [comment]
Use location format as specified in issue #7 's thread

**Comment by Rushi98** [comment]
a "venue" will have following attributes:
1. `venueName` (ex: "auditorium")
2. `latitude` (a float value of at least 6 digits after decimal place, positive is for north ex: 15.392973)
3. `longitude` (a float value of at least 6 digits after decimal place, positive is for east ex: 73.880493)

**Comment by rrgodhorus** [comment]
And where do I pull these values from?
From firebase?

**Comment by Rushi98** [comment]
yes. Also make the activity such that it's possible to launch it with only a subset of locations
